name: SnowyRPGPlugin
version: 2.4
author: LoudbookAndSnowedSeal
main: me.loudsnow.mcplug.Main
description: Snowy RPG Plugin
api-version: 1.18
commands:
  booktest:
    description: Test for Book
    usage: /booktest
  banker:
    description: Get the bank (devs only)
    usage: /banker
  getwindstep:
    description: Get Windstep [REMOVE]
    usage: /getwindstep
  getmeteorslam:
    description: Get Meteor Slam
    usage: /getmeteorslam
  getshadowleap:
    description: Get Shadowleap
    usage: /getshadowleap
  getdesolation:
    description: Get Desolation
    usage: /getdesolation
  gettruedesolation:
    description: Get Awakened Desolation
    usage: /gettruedesolation
  getstarterdagger:
    description: Get basic dagger
    usage: /getstarterdagger
  getstartersword:
    description: Get basic sword
    usage: /getstartersword
  getrookieglider:
    description: Get Rookie Glider
    usage: /getrookieglider
  getflameblade:
    description: Get Flameblade
    usage: /getflameblade
  getsalvation:
    description: Get Salvation
    usage: /getsalvation
  getforestsword:
    description: Get Forest Sword
    usage: /getforestsword
  getglowingpendant:
    description: Get Glowing Pendant
    usage: /getglowingpendant
  hashmaptest:
    description: Test Hash Map
    usage: /hashmashtest
  whistle:
    description: Summon Horse
    usage: /whistle
  reloadbot:
    description: Reload Discord Bot
    usage: /reloadbot
  report:
    description: Report Something
    usage: /report
  clearhash:
    description: Clear Hash
    usage: /clearhash
  testspawn:
    description: Test Spawning Algorithm
    usage: /testspawn