name: SnowySMPPlugin
version: 0.1
author: LoudbookAndSnowedSeal
main: me.loudsnow.mcplug.Main
api-version: 1.18
commands:
  booktest:
    description: Test for Book
    usage: /booktest
  banker:
    description: Get the bank (devs only)
    usage: /banker
  getwindstep:
    description: Get Windstep [REMOVE]
    usage: /getwindstep
